name: CI-CD-Fluxo

on:
  push:
    branches: [ "main", "desenvolvimento" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "PROJETO DEVOPS" 

    steps:
      - uses: actions/checkout@v4

      - name: Usar Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes
        run: npm test -- --watchAll=false

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Executando Deploy
        run: echo "Fazendo o deploy para producao..."

      - name: Enviar alerta para Discord
        if: always()
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{\"content\": \"🚀 Pipeline executado com status: ${{ job.status }}\"}" \
          ${{ secrets.DISCORD_WEBHOOK }}
