name: CI-CD-Fluxo

on:
  push:
    branches: [ "main", "desenvolvimento" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Define que todos os passos abaixo devem rodar dentro da sua pasta de projeto
    defaults:
      run:
        working-directory: "Projeto DevOps"

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'Projeto DevOps/package-lock.json'

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes
        run: npm test -- --watchAll=false

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Executando Deploy
        run: echo "Fazendo o deploy para producao..."

      - name: Enviar alerta para Discord
        if: always()
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{\"content\": \"🚀 Pipeline executado com status: ${{ job.status }}\"}" \
          ${{ secrets.DISCORD_WEBHOOK }}